### ISSUE TITLE
大佬中奖之后的卡片背景是‘虎’，怎么能改成龙或者别的，或者是在哪改的

### ISSUE THREAD

**Issue by WendelYu** [GAtomis/lottery-web#13]

**Comment by GAtomis** [comment]
卡背在css文件中修改

**Comment by GAtomis** [comment]
index.css文件中 .prize.element

**Comment by WendelYu** [comment]
> index.css文件中 .prize.element

我昨天找到改中奖之后的卡片位置的地方了，但是我改成本地引用后不生效

**Comment by GAtomis** [comment]
> > index.css文件中 .prize.element
> 
> 我昨天找到改中奖之后的卡片位置的地方了，但是我改成本地引用后不生效

相对路径引用./xxx/xxx
