### ISSUE TITLE
。

### ISSUE THREAD

**Issue by redaiFish** [GAtomis/lottery-web#14]

**Comment by redaiFish** [comment]
我现在是用yarn dev进入的，但是文件夹中的index.html打开后css的东西加载不出来

**Comment by GAtomis** [comment]
入口啥意思

**Comment by redaiFish** [comment]
老哥我发现我是node-sass 在构建失败

**Comment by GAtomis** [comment]
如果构建失败尝试切换到官方的源进行重新安装包操作


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GAtomis/lottery-web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月30日(星期二) 下午5:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GAtomis/lottery-web] 。 (Issue #14)





 
老哥我发现我是node-sass 在构建失败
