### ISSUE TITLE
没学过前端的小白求教背景图片问题

### ISSUE THREAD

**Issue by DesignBestC** [GAtomis/lottery-web#6]
求教大佬，如果要把项目背景图片、红包图片都改成本地文件要怎么改

**Comment by GAtomis** [comment]
可以加我vx15821450802




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GAtomis/lottery-web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月8日(星期一) 上午9:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[GAtomis/lottery-web] 没学过前端的小白求教背景图片问题 (Issue #6)





 
求教大佬，如果要把项目背景图片、红包图片都改成本地文件要怎么改

**Comment by DesignBestC** [comment]
好的，我加您了

**Comment by DesignBestC** [comment]
大佬帮忙解决问题了，非常感谢
